### ISSUE TITLE
脚本API:  GM_setClipboard 无效

### ISSUE THREAD

**Issue by jian263994241** [uumomentum/block100#14]
iOS: 15.5/16.0b3
app: 4.1.3

**Comment by jian263994241** [comment]
```js
// ==UserScript==
// @name         magnet_copy2
// @version      0.2
// @description  try to take over the world!
// @match        *://*/*
// @grant        GM_setClipboard
// ==/UserScript==

const toLocaleLowerCase = (string) =>
  String.prototype.toLocaleLowerCase.call(string);

(function () {
  'use strict';

  document.addEventListener('click', (e) => {
    const currentNode = e.target;
    const tagName = toLocaleLowerCase(currentNode.tagName);
    GM_setClipboard(tagName);
  });
})();
```

**Comment by jian263994241** [comment]
最新版已经修复了.   这里怎么没有人回复呢?

**Comment by sirry5390** [comment]
> ```js
> 
> // ==UserScript==
> 
> // @name         magnet_copy2
> 
> // @version      0.2
> 
> // @description  try to take over the world!
> 
> // @match        *://*/*
> 
> // @grant        GM_setClipboard
> 
> // ==/UserScript==
> 
> 
> 
> const toLocaleLowerCase = (string) =>
> 
>   String.prototype.toLocaleLowerCase.call(string);
> 
> 
> 
> (function () {
> 
>   'use strict';
> 
> 
> 
>   document.addEventListener('click', (e) => {
> 
>     const currentNode = e.target;
> 
>     const tagName = toLocaleLowerCase(currentNode.tagName);
> 
>     GM_setClipboard(tagName);
> 
>   });
> 
> })();
> 
> ```
