### ISSUE TITLE
[Suggestion] 一种比阻止更好的思路 (zhihu.com)

### ISSUE THREAD

**Issue by zhmushan** [uumomentum/block100#5]
我是 block100 的买断用户, 有一个比较好的思路, 写了个插件自用, 没钱发布, 希望能给作者一点启发

源码链接: https://github.com/zhmushan-zone/HelloZhiHu/tree/main

## 修改桌面端网站, 而不是阻止移动端网站调起 App
- 知乎不可能抛弃桌面端的流量
- 桌面端没有 App, 于是不存在调端, 不需要与厂商博弈
- 现代 Web 适配容易, 我的 demo 仅仅 100 行代码, 已经让我抛弃了知乎 App

如果您觉得这个建议不错, 可以随意的处置我的代码和 idea, 当然如果能提一嘴我的 MIT 版权, 我也会非常开心的啦

**Comment by uumomentum** [comment]
思路不错，非常感谢！
我们考虑下这个建议。
