### ISSUE TITLE
扩展更新了，怎么GitHub上代码不更新？

### ISSUE THREAD

**Issue by LoneFireBlossom** [uumomentum/block100#6]
贵司（这里没有贬义）开发流程不含GitHub……？我总怀疑这个开源是做做样子

**Comment by starxg** [comment]
毕竟出VIP了，目测此项目已死。

![image](https://user-images.githubusercontent.com/34997494/144768635-e03a1a91-8151-43cb-8eb9-9a46dad8c30b.png)

**Comment by AlanDinkle** [comment]
> 毕竟出VIP了，目测此项目已死。
> 
> ![image](https://user-images.githubusercontent.com/34997494/144768635-e03a1a91-8151-43cb-8eb9-9a46dad8c30b.png)

话也不能这么说，出VIP能理解，darkreader也收费，但是代码好歹得同步吧，至少也一周同步一次。

**Comment by uumomentum** [comment]
现在开发任务非常繁忙，过段时间会同步代码的。

**Comment by Bohan-Song** [comment]
支持 感谢开源

**Comment by ErnestDong** [comment]
看到开源激情开通永久VIP支持，没想到停更了😮‍💨希望至少拦截广告的部分还能坚持下去
